In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report as cr
from sklearn.metrics import confusion_matrix as cm
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics

In [17]:
data=pd.read_csv("hepatitis.csv")
print(data)
df_enc=data.apply(LabelEncoder().fit_transform)
x=np.array(data)[:,:-1]
y=np.array(df_enc)[:,-1]

     class  age  sex  steroid  antivirals  fatigue  malaise  anorexia  \
0        2   30    2        1           2        2        2         2   
1        2   50    1        1           2        1        2         2   
2        2   78    1        2           2        1        2         2   
3        2   34    1        2           2        2        2         2   
4        2   34    1        2           2        2        2         2   
..     ...  ...  ...      ...         ...      ...      ...       ...   
137      1   46    1        2           2        1        1         1   
138      2   44    1        2           2        1        2         2   
139      2   61    1        1           2        1        1         2   
140      2   53    2        1           2        1        2         2   
141      1   43    1        2           2        1        2         2   

     liver_big  liver_firm  spleen_palable  spiders  ascites  varices  \
0            1           2               2        

In [3]:
print(x)
print(y)

[[ 2.  30.   2.  ... 18.   4.  61. ]
 [ 2.  50.   1.  ... 42.   3.5 61. ]
 [ 2.  78.   1.  ... 32.   4.  61. ]
 ...
 [ 2.  61.   1.  ... 20.   4.1 61. ]
 [ 2.  53.   2.  ... 19.   4.1 48. ]
 [ 1.  43.   1.  ... 19.   3.1 42. ]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
class LogisticRegressionn:
    def __init__(self, learning_rate=0.001, n_iters=5000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        # init parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        # gradient descent
        for _ in range(self.n_iters):
            # approximate y with linear combination of weights and x, plus bias
            for idx,x_i in enumerate(X):
            # approximate y with linear combination of weights and x, plus bias
                linear_model = np.dot(x_i, self.weights) + self.bias
            # apply sigmoid function
                y_predicted = self._sigmoid(linear_model)
            # compute gradients
                dw = (1 / n_samples) * np.dot(x_i, (y_predicted - y[idx]))
                db = (1 / n_samples) * np.sum(y_predicted - y[idx])
            # update parameters
                self.weights -= self.lr * dw
                self.bias -= self.lr * db

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self._sigmoid(linear_model)
        y_predicted_cls = [1 if i > 0.5 else 0 for i in y_predicted]
        return np.array(y_predicted_cls)

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def _relu(self,x):
        return x*(x>0)

    def  _tanh(self,x):
        return np.tanh(x)
    


   


In [6]:
model=LogisticRegressionn()
model.fit(x_train,y_train)

In [7]:
y_pred=model.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1])

In [8]:
print(cm(y_test,y_pred))
print(cr(y_test,y_pred))

[[17  2]
 [ 5  5]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.83        19
           1       0.71      0.50      0.59        10

    accuracy                           0.76        29
   macro avg       0.74      0.70      0.71        29
weighted avg       0.75      0.76      0.75        29



In [11]:
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
r2 = metrics.r2_score(y_test,y_pred)

print(mae)
print(mse)
print(r2)

0.2413793103448276
0.2413793103448276
-0.06842105263157916


implementing logistic regression using sklearn package

In [13]:
model2=LogisticRegression(max_iter=1000)
model2.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [14]:
y_pred2=model2.predict(x_test)

In [15]:
print(cm(y_test,y_pred2))
print(cr(y_test,y_pred2))

[[16  3]
 [ 3  7]]
              precision    recall  f1-score   support

           0       0.84      0.84      0.84        19
           1       0.70      0.70      0.70        10

    accuracy                           0.79        29
   macro avg       0.77      0.77      0.77        29
weighted avg       0.79      0.79      0.79        29



In [16]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test, y_pred2)
mse = metrics.mean_squared_error(y_test, y_pred2)
r2 = metrics.r2_score(y_test,y_pred2)

print(mae)
print(mse)
print(r2)


0.20689655172413793
0.20689655172413793
0.0842105263157894
